DROP TABLE IF EXISTS TB_HQ;
DROP TABLE IF EXISTS TB_FEED;

-- TABELA HQ --
CREATE TABLE TB_HQ (
  ID_HQ INT AUTO_INCREMENT  PRIMARY KEY,
  NOME_HQ VARCHAR(250) NOT NULL,
  CAPA_HQ VARCHAR(50) NOT NULL,
  DESCRICAO_HQ VARCHAR(250) NOT NULL
);

INSERT INTO TB_HQ (NOME_HQ, CAPA_HQ, DESCRICAO_HQ) VALUES
  ('Spider-Man Geddon', 'hq1.jpg', 'Spider-Man no mundo rock'),
  ('Spider-Man Geddon', 'hq2.jpg', 'Spide-Man de volta ao Queens'),
  ('Ultimate Spider-Man', 'hq3.jpg', 'Spider-Man da nova geração');
 
 
--- TABELA LOGIN ---
CREATE TABLE TB_LOGIN (
  ID_USUARIO VARCHAR (25) NOT NULL,
  NOME_USUARIO VARCHAR(50) NOT NULL,
  SENHA_USUARIO VARCHAR(50) NOT NULL
);

INSERT INTO TB_LOGIN (ID_USUARIO, NOME_USUARIO, SENHA_USUARIO) VALUES
	('b4tman', 'Lucas', '123');
	
CREATE TABLE USERS(
	USERNAME VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR_IGNORECASE(200) NOT NULL,
	ENABLED BOOLEAN NOT NULL
);

CREATE TABLE AUTHORITIES (
	USERNAME VARCHAR_IGNORECASE(50) NOT NULL,
	AUTHORITY VARCHAR_IGNORECASE(50) NOT NULL,
	CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('bob', '{noop}123', TRUE);
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('bob', 'ROLE_USER');

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('sara', '{noop}234', TRUE);
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('sara', 'ROLE_ADMIN');